export const services = {
  water: { title:'Water', eyebrow:'01 / Utility Services', subtitle:'Water Utility Solutions', image:'/images/water.jpg', intro:'Every development is unique and needs to be planned carefully. We tailor our services to meet your requirements, no matter how complex the project.', bullets:['Commercial and domestic water connection','Commercial and domestic water disconnection or relocation','Temporary water supply','Water chlorination testing','Provision and install of water meters','Private water pipe installation','Testing, swabbing and cleaning of newly installed pipes','Associated works: excavation, backfilling and reinstatement'], accreditation:'WIRS Accredited' },
  gas: { title:'Gas', eyebrow:'02 / Utility Services', subtitle:'Gas Utility Solutions', image:'/images/gas.jpg', intro:'We understand the challenges that can arise when planning gas installation for any development. Our team designs and implements safe, efficient gas solutions tailored to each project.', bullets:['Design and approval of new gas networks','Application to relevant authorities for supply','Gas meter installation, removal or relocation','Domestic and commercial gas mains install and connection','LPG installs','Service disconnection','Gas pipe installation','Full construction packages','Associated works: excavation, backfilling and reinstatement'], accreditation:'GIRS Accredited' },
  electricity: { title:'Electricity', eyebrow:'03 / Utility Services', subtitle:'Electrical Utility Solutions', image:'/images/electricity.jpg', intro:'Whether domestic, industrial or commercial, our qualified electrical experts design the most appropriate, safe and efficient electrical solution.', bullets:['Electrical design and supply','Installation of LV up to 11kv','Jointing','Substation installation and commissioning','Substation removal and decommissioning','Power cable installation','Cable laying','Diversions','Temporary supply','Associated works: excavation, backfilling and reinstatement'], accreditation:'NERS Accredited' },
  bt: { title:'BT', eyebrow:'04 / Utility Services', subtitle:'BT Utility Solutions', image:'/images/bt.jpg', intro:'Whatever size or scale your project, our expert team designs and plans efficient telecoms infrastructure and ensures delivery is ready for adoption.', bullets:['Single-lay duct for BT or other comms providers','Multi-lay duct for BT or other comms providers','Provision and install of ancillary equipment','Boxes and manholes','Readiness for adoption','Installation of duct, box and draw cords','Associated reinstatement works'], accreditation:'Experienced Telecoms Team' },
  'new-builds': { title:'New Builds', eyebrow:'05 / Utility Services', subtitle:'New Build Utility Solutions', image:'/images/new-builds.jpg', intro:'We design, plan and manage the installation and connection of all utilities as a single project, reducing complexity, cost and disruption.', bullets:['Comprehensive design and planning','Electricity installation and connections','Gas installation and connections','Water installation and connections','Telecoms ducting and private networks','Complete utilities project management','Commercial or domestic developments','Co-ordination of service connections'], accreditation:'Fully Accredited' },
  'grab-wagon-hire': { title:'Grab Wagon', eyebrow:'06 / Civil Engineering', subtitle:'Grab Wagon Services', image:'/images/grab-wagon.jpg', intro:'Our modern fleet provides efficient and cost-effective site clearance and material removal support alongside utility works.', bullets:['Site clearance','Material removal','Utility excavation support','Commercial and domestic projects'], accreditation:'Integrated Site Support' },
};

export const nav = [
  ['Water','/water'],['Gas','/gas'],['Electricity','/electricity'],['BT','/bt'],['New Builds','/new-builds'],['Grab Wagon','/grab-wagon-hire'],['News','/news']
];

export const genericPages = {
  about:{title:'About',kicker:'Company Overview',body:'J. Geraghty Ltd was founded in 2014 after years of hands-on multi-utility experience. Today the company supports commercial organisations and domestic clients across the UK with complete water, gas, electricity and telecoms infrastructure management.'},
  values:{title:'Our Core Values',kicker:'How We Work',body:'Safety & Wellbeing. Client-First Delivery. Teamwork & Collaboration. Technical Excellence. Accountability & Transparency. Integrity & Compliance.'},
  news:{title:'News',kicker:'Project Updates',body:'Updates, projects and company news from J. Geraghty Utility Services.'},
  team:{title:'Our Team',kicker:'Experts You Can Trust',body:'Our engineering and project teams bring extensive industry experience to every project and understand the technical, regulatory and operational requirements of modern utility infrastructure.'},
  faq:{title:'FAQs',kicker:'Utility Questions',body:'Answers to frequently asked questions about utility installation, project preparation, accreditations and delivery.'},
  recruitment:{title:'Recruitment',kicker:'Join The Team',body:'Explore opportunities to work with J. Geraghty Utility Services.'},
  testimonials:{title:'Testimonials',kicker:'Client Experience',body:'Trusted utility delivery for commercial and domestic developments across the UK.'},
  policies:{title:'Policies',kicker:'Governance',body:'Company policies covering information security, corporate responsibility, anti-slavery, equality, quality, environment, health and safety, data protection and anti-bribery.'},
  privacy:{title:'Privacy Policy',kicker:'Data & Privacy',body:'Information about how J. Geraghty Ltd handles personal data and privacy.'},
  contact:{title:'Contact',kicker:'Book A Quotation',body:'Our friendly team are here to help with all enquiries and quotations. Tel: 01422 419980 · J. Geraghty Ltd, Lowfields Way, Lowfields Industrial Estate, Elland, Halifax, HX5 9DA.'}
};
